name: netflix

profile: netflix

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  netflix:
    +database: MOVIELENS
    +schema: ANALYTICS
    +materialized: view
    dim:
      +materialized: table
    fact:
      +materialized: table
