netflix:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: POHRMQJ-SUB19479
      user: dbt
      password: dbtPassword123
      role: TRANSFORM
      warehouse: COMPUTE_WH
      database: MOVIELENS
      schema: RAW
      threads: 4
      client_session_keep_alive: False
